global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: spark
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:4040"
          - "host.docker.internal:4041"
          - "host.docker.internal:4042"

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka1:7071"]
