services:
  kafka1:
    image: apache/kafka:3.7.0
    ports:
      - "9092:9092"
      - "7071:7071"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka
      EXTRA_ARGS: >
        -javaagent:/opt/jmx/jmx_prometheus_javaagent.jar=7071:/opt/jmx/kafka-jmx.yml
    volumes:
      - ./main/monitoring/jmx:/opt/jmx
  
  minio1:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./main/storage/data/minio:/data

  prometheus1:
    image: prom/prometheus:latest
    container_name: prometheus1
    volumes:
      - ./main/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana1:
    image: grafana/grafana:latest
    container_name: grafana1
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./main/grafana/provisioning:/etc/grafana/provisioning
      - ./main/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus1
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  trino1:
    image: trinodb/trino:438
    container_name: trino1
    ports:
      - "8080:8080"
    volumes:
      - ./main/trino:/etc/trino
    depends_on:
      - minio1

volumes:
  grafana_data:
  postgres_data:
  